name: example-environment
channels:
  - conda-forge
dependencies:
  - pandas-profiling=1.4.2
  - matplotlib=2.2.2
  - numpy=1.14.3
  - pandas=0.23.0
  - seaborn=0.9.0
  - scikit-learn=0.21.1
  - plotly